### ISSUE TITLE
with no errors, it actually returns undefined, not null.

### ISSUE THREAD

**Issue by Satyam** [ratehub/check-prop-types#1]
There is no actual return at the end of the function if it doesn't return an error earlier on.

**Comment by uniphil** [comment]
Hi @Satyam! Thanks for the report, and sorry for my delayed response -- I missed the notification on this issue.

I will probably correct the docs to specify that it it returns nothing/undefined on success, not `null`, unless you have a use-case for expecting `null` specifically?

**Comment by Satyam** [comment]
No special case at all.  As long as docs and code agree, I'm happy.

**Comment by uniphil** [comment]
Fixed docs, added stricter tests, and published for npm readme fix v1.1.1

Good catch and thanks for the report @Satyam !
